channels:
 - conda-forge
dependencies:
 - python=3.8*
 - s3fs
 - dask
 - pandas
 - distributed
 - rechunker
 - fsspec
 - numcodecs
 - intake-xarray
 - prefect
 - xarray
 - netcdf4
 - scipy
 - zarr
 - cdsapi
 - python-blosc
 - cytoolz
 - lz4
 - nomkl
 - tini==0.18.0

